ALTER TABLE notes ADD COLUMN IF NOT EXISTS id BIGSERIAL;
ALTER TABLE notes DROP CONSTRAINT IF EXISTS notes_pkey;
ALTER TABLE notes ADD PRIMARY KEY (id);

ALTER TABLE note_versions ADD COLUMN IF NOT EXISTS id BIGSERIAL;
ALTER TABLE note_versions DROP CONSTRAINT IF EXISTS note_versions_pkey;
ALTER TABLE note_versions ADD PRIMARY KEY (id);