ALTER TABLE notes DROP CONSTRAINT IF EXISTS notes_pkey;
ALTER TABLE notes DROP COLUMN IF EXISTS id;

ALTER TABLE note_versions DROP CONSTRAINT IF EXISTS note_versions_pkey;
ALTER TABLE note_versions DROP COLUMN IF EXISTS id;